name = "webmaster-domain-tools"
compatibility_date = "2024-01-01"

[build]
command = "cd webapp && npm install && npm run build"
cwd = "."
watch_dirs = ["webapp/src"]

[build.upload]
format = "service-worker"
dir = "webapp/dist"
main = ""

[[pages_build_output_dir]]
  dir = "webapp/dist"

[env.production]
name = "webmaster-domain-tools"

[env.preview]
name = "webmaster-domain-tools-preview"
