name = "webmaster-domain-tools"
compatibility_date = "2024-11-18"
pages_build_output_dir = "webapp/dist"

[env.production]
name = "webmaster-domain-tools"

[env.preview]
name = "webmaster-domain-tools-preview"
